### ISSUE TITLE
behavior in China?

### ISSUE THREAD

**Issue by razmaimon** [AdevintaSpain/Leku#247]
China is restricting access to Google Api's.
i'm guessing that this library won't function well in China (under Chinese network) due to no connection to google.maps

can someone tell us what should we expect in the library's behavior when opened in China?

thanks.

**Comment by ferranpons** [comment]
Hi @razmaimon !

Since this library is based on the Google APIs it's possible that the behavior would be affected on China. However, it would be possible to use your own Geocoder APIs or use an alternative if you create your own DataSource and link it to the library. But is not an easy task right now because there is no documentation on how to do it. Alternatively, you could create your own DataSource and create a PR to include it on the library.

**Comment by razmaimon** [comment]
i am not worried that it won't work... Chinese understand that this is based on google(we have a manual form for them...)
we are trying to understand the fallbacks we need to look for in order to discover these cases...
how will the library behave, what exception(if any) will it throw... etc.

**Comment by ferranpons** [comment]
I understand... well It depends on what APIs are affected, since we only use the ones that provides Google, you will need to know if the default Android Geocoder, Google Places are affected and the common Google Maps APIs used by Maps itself.
It could go from retrieving the locations using the search bar to the naming retrieved after selecting a location manually, if are not running it only will show the latitude and longitude values, If you're lucky to load the map itself.
