### ISSUE TITLE
How do I hide the focus button and white area?

### ISSUE THREAD

**Issue by muratdoglu** [AdevintaSpain/Leku#287]
![Screenshot_20191030-193838_Taksim](https://user-images.githubusercontent.com/19818531/67879014-4b8b8880-fb4d-11e9-8f32-fba4d8fa875e.jpg)

How do I hide the focus button and white area?

**Comment by muratdoglu** [comment]
@ferranpons can you help me?

**Comment by ferranpons** [comment]
Hi @muratdoglu 

I'm afraid that there is no way to hide the button and the address layer. It was intended to work this way, because we always want to select a location and accept that location afterwards. If you need to hide those components I suggest you to use your own activity and use the Leku "Presenter" component to customize it to your needs.
Otherwise, If you are experiencing a white and empty component that could be a bug, It should show you the address for that location and the buttons must be fully visible.

**Comment by fi8er1** [comment]
The buttons are not visible for me either....

**Comment by ferranpons** [comment]
In the latest version you can hide the remove the location card (v7.0.0)
