### ISSUE TITLE
Leku JAVA Please

### ISSUE THREAD

**Issue by lisares** [AdevintaSpain/Leku#293]
Please i want JAVA code of your SDK, because KOTLIN, i don't like it

**Comment by ferranpons** [comment]
I'm sorry this is not going to happen. Anyway, you could still use Java code because Kotlin is interoperable with Java.

Maybe you don't like it but there are some vantages of using Kotlin instead of Java. Check out this link:
[https://dzone.com/articles/what-are-the-biggest-advantages-of-kotlin-over-jav](https://dzone.com/articles/what-are-the-biggest-advantages-of-kotlin-over-jav)
